[package]
name = "mogbox-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cpal = { workspace = true }
symphonia = { workspace = true }
mogbox-io = { path = "../io" }
